credstash.py
=> HMAC after encrypt

credstash.py
making one call to KMS per encrypt/decrypt instead of two. Generate a 64 byte key and split it for encryption and hmac
=> make single GenerateKey call to KMS, split for encrypt/hmac

README.md
=> Fixed teensy typo in readme

README.md, credstash.py
* makes credstash actually respect the region setting for `setup`
* allow the user to specify the region in `$AWS_DEFAULT_REGION`
=> region fixes 

README.md, credstash.py
I added json yaml and csv output. It would be trivial to add any more that come to mind.
=> Add getall feature to fetch all possible credentials

credstash.py
=> report the latest version in the store if the conditional put fails

credstash.py
=> make argparse not explode on python3

README.md, credstash.py
=> added flag for put to autoincrement version

credstash.py, setup.py
This ports all remaining uses of boto2 over to boto3 (see #38).
=> Remove boto2

credstash.py
close #52 
There was a change in the DDB `put_item` behavior in Boto3. Where Boto2 would not overwrite items by default, boto3 will. This change fixes that, so that items will not be silently overwritten. It also fixes an improperly caught exception (again, boto3 changes)
=> fix conditional put and exception catching

README.md, credstash-migrate-autoversion.py, credstash.py, setup.py
=> auto version fix

credstash.py
Currently credstash manually replicate parts of Boto3's configuration data
parsing - it reads its command line argument, falling back to
AWS_DEFAULT_REGION, and after that falling back to us-east-1.
Per the Boto3 documentation:
https://boto3.readthedocs.org/en/latest/guide/configuration.html
it should also read ~/.aws/config for the region setting if it is not set
in the environment.
To avoid reimplementing the configuration parsing in achieving this:
- use the args.region command line argument (if unset this will be None,
which is the default for Boto3 methods anyway).
- try and get the dynamodb resource using this region setting
- if it fails, then as a last resort use the DEFAULT_REGION setting
hard-coded to us-east-1
=> Make credstash honor ~/.aws/config region setting

credstash.py
Added a new parameter, `profile_name`, to the following methods:
- `getHighestVersion`
- `listSecrets`
- `putSecret`
- `getAllSecrets`
- `getSecret`
- `deleteSecrets`
- `createDdbTable`
This parameter allows the user to pass in a profile name as an optional argument. This profile name is then used to generate an AWS Boto session, which is then used to create clients and resources using the credentials in the given profile.
Basically, it lets the user specify the AWS profile they'd like to use when calling the listed methods.
=> Added ability to pass AWS profiles as arguments.

credstash.py
Added the ability to pass a boto profile through the command line via the argument `-p [profile]`.
=> Added profile command-line argument.

credstash.py
.. in addition to argument passing or a file.
=> In the 'put' action, the value can be read from stdin

credstash.py
=> Fallback to the default region if AWS_DEFAULT_REGION isn't set in the environment

credstash.py, setup.cfg, setup.py, tests/runtests.py
Formatting fixes to pass `flake8` static analysis. Also adds a `setup.cfg` to configure `flake8`
=> Fix up formatting to pass flake8

.travis.yml, tests/expand_wildcard_tests.py, tests/key_pair_tests.py, tests/pad_left_tests.py
moved tests to separate file per class and figured out why nosetests . wasn't working.
=> expanded tests

credstash.py
Our security team advised us we needed to use SHA512 instead of SHA256, so rather than hardcode everything, we decided to generalize it a bit!
You can use "credstash put mykey mypass -d SHA512" to encrypt the value with SHA512 (or a number of others). It inserts the name of the hashing algorithm into the digest column of DynamoDB so "get" knows how to decrypt it. If the digest field for a key does not have a value, it defaults to SHA256 so it can be backward-compatible.
=> Added ability to specify hashing algorithm on "put" with -d

credstash.py, tests/key_pair_tests.py, tests/pad_left_tests.py
Minor ones this time:
-  avoid unused import warnings
-  fix up infix operations to have proper spacing
-  whitespace
=> More flake8 fixes

.travis.yml, credstash.py, requirements.txt, setup.py
Back-ported commits from [credsmash](https://github.com/3stack-software/credsmash)
- https://github.com/3stack-software/credsmash/commit/031db4e3bfbd8e11a585f6325445d3ce9f4a1339
- https://github.com/3stack-software/credsmash/commit/2299a05ab62c913528a1f4cd06d059845205d385
There was an issue with pypy tests https://github.com/travis-ci/travis-ci/issues/4756
Fixes #96
=> Cryptography - Switch from `pycrypto` to `cryptography`

credstash.py
fixes for the documentation of several options. also replace the use of
`os.patch.basename(__file__)` with `sys.argv[0]` to acheive a more
consistent form of the program name (and cleaner when installed via `pip`)
=> improve help text output

README.md
updates the readme to include references to other projects and to include the iam policy for creating the ddb table
=> update README. close #119. close #118

credstash.py
Fixes regression with non default digest introduced in https://github.com/fugue/credstash/pull/116 .
=> fix non default digest method

credstash.py
I'd like to propose this change which speeds up credstash. This improve was achieved by caching the the `kms` client and `dynamodb` resource instead of getting a new one each time during `credstash getall`.
As an example I've got 200+ rows in my dynamodb and here are the results `credstash getall` when compared against `credstash 1.12.0`:
`credstash 1.12.0`:
```
$ credstash list | wc -l                                                    
218
$ time credstash getall
...
real    0m56.437s
user    0m4.605s
sys     0m0.191s
```
This PR's version of credstash:
```
$ credstash list | wc -l
218
$ time credstash getall
real    0m14.232s
user    0m0.978s
sys     0m0.051s
```
Let me know what you think!
~Rob
=> Speed up by caching aws resources and clients

README.md
Previous package wasn't able to decrypt failing at the hmac check for some reason
this one is way more recent both in design and implementation
=> Changed nodejs client to actually working one

credstash.py
This matches the formatting already available on the `getall` action, so that the results of using a wildcard in the get command (to get a plurality of keys but not all of them) can be formatted.
=> Allow a `--format` parameter to `get` action

credstash.py
I'm often creating new credstash tables. This lets me import existing credentials very handily.
=> Add putall command to import from a getall formatted json.

credstash.py
Set default version to what the help output says it will.
Fixes #181
=> Resolves #181 true up default version with help text

README.md, credstash.py
Much faster `getall` performance when fetching larger tables. :smiley_cat:
=> Use a thread pool to fetch many values from DDB in parallel

credstash.py
This PR adds an option, `--prompt`, to prompt the user for the password from stdin.
=> Add option to prompt for password

changelog.md
@alex-luminal Noticed this typo while working on strange issue with  cryptography version ! Solved it.
=> Fix typo in changelog !

credstash.py
=> Add a default tag when creating the dynamoDB table

credstash.py
backing this merge out because it breaks getall
=> Revert "Resolves #73: Support binary secrets"

credstash.py
Also switch to `query` as that's much more efficient
=> Fix delete for large tables

credstash.py
=> Specify table via environment variable

credstash.py
Hi,
I've added a method to so the user can perform auto-versioning without using the cli command. 
I found this very useful when working on automation of processes related to AWS.
=> added autoversioning with putSecret

credstash.py
I've reverted a commit originally made by me but with wrong author details. The function have been removed and once PR have been approved, a new PR containing the function will be made as suggested and by @mike-luminal
=> removed autoversioning function (original commit with wrong author)

credstash.py
New commit with auto-versioning function re-added. Function initially removed to correct for wrong author details when commit was made.  Commit originally approved by @mike-luminal
=> Re-added function for auto-versioning with put secret

credstash.py
Sorry I didn't catch this earlier! Once I added the validation on the arguments `tags` started coming through as a list of a list. If I get a chance I'll create a follow up PR to create some behavioral tests.
=> Resolves #246 Fix bug in tagging feature

credstash.py
Resolve #261 
Return {} when there are no secrets.
=> check for empty names list in getall

credstash.py
Resolves #276 
The `clean_fail` decorator that suppressed error output for the `credstash` CLI catches all errors. This behavior is undesirable when `credstash` is imported as a library. This PR adds a conditional to `clean_fail` so it will only catch errors when run as a command.
=> Don't catch errors when imported as lib

README.md
Resolve #278 
Update readme with latest usage.
=> CS-278 update usage in README
