fugue/credstash

- README.md
- credstash.py
Fixed one typo in credstash.py and seven typos in README.md. (Line 17 of the README replaces "an" with "and"; "it's" with "its")
> Fixing typos

- README.md
- credstash.py
- setup.py
This PR adds support for [Encryption Contexts](http://docs.aws.amazon.com/kms/latest/developerguide/encrypt-context.html). I've implemented it so as to be backwards compatible with all existing credstash interfaces.
I had to change from using a single global argparse to use [subparsers](https://docs.python.org/2/library/argparse.html#sub-commands) in order to allow for the differing expected positional arguments for each action. Previously this was worked around in the `put` command by having a `nargs='?'` setting for the `value` argument. Using subparsers will accommodate the differing expected positional arguments. It also makes the usage clearer as to what's expected for each different action.
I figured using positional arguments for the encryption contexts in a `key=value` format …
> Adding support for KMS "encryption context"

- README.md
- credstash.py
`-i` INFILE broken in credstash 1.3.1. This change replaces the `-i` option which breaks compatibility with anyone previously using the `-i` option.
Relates to issue #19
> Replaces the `-i` INFILE option with an `@` prefixed value

- README.md
- credstash.py
This PR adds wildcard functionality.
For anyone with existing credentials where the name of the credential contains the `*` character, this could change their experience. For example, a user has these credentials stored
Name | Value
---|---
`DBPassword` | `s3cret`
`Weird*credential*name` | `an0thersecr3t`
`Weirder-credential-has-this-name` | `y3tan0thers3cret`
who ran the following command
```
credstash get Weird*credential*name
```
Would get this with the old code
```
an0thersecr3t
```
and would get this with the code in this PR
```
{"Weird*credential*name":"an0thersecr3t",
"Weirder-credential-has-this-name":"y3tan0thers3cret"}
```
I think that the likelyhood that people are using the `*` asterisk character in credential names is low but it's something to consider.
The other impact of …
> Add wildcard to get

- credstash.py
Having the `import json` in a function was causing an UnboundLocalError to be thrown when doing a wildcard-get. This change moves imports out of functions
> moved json import out of function to fix UnboundLocalError; arranged imports

- credstash.py
The pre-python-2.7 replacement dictionary comprehension code strips the last encryption context
> Fixes bug where last encryption context is lost

- setup.py
Small change to make credstash install as a single-file python module, allowing it to be imported.
> make credstash install as a python module

- credstash.py
- optional-requirements.txt
- requirements.txt
- setup.py
As PyYAML uses distutils Extensions for libyaml bindings installation requires -devel packages and gcc.
> Make PyYAML optional

- credstash.py
on python 2.6, argparser calls `value_or_filename` with an empty string before it passes the `value` param to to `value_or_filename`. the index check blows up on an empty string. This fixes that.
> fix for python 2.6 argparser

- credstash.py
Python 3 does not have StringIO.StringIO(), it has io.StringIO(). This change tries to use the python 2 StringIO, and uses io.StringIO if its not there.
> use io.StringIO on python3

- credstash.py
- requirements.txt
using python3 with boto.kms breaks on decrypt/encrypt because of python3's handling of byte arrays
> make credstash python3 compatible by using boto3 kms

- requirements.txt
- setup.py
also, it doesn't appear to be used anywhere.
> wsgiref==0.1.2 fails install on python3

- credstash.py
- setup.py
fixes #42 by importing InvalidCiphertextException properly.
> catching exceptions from kms.decrpyt() fails

- README.md
- credstash-migrate-autoversion.py
Made a tweak and did a PR this time so we could discuss / tweak further. Here's the output at present:
```
scramble:credstash dom-at-luminal$ ./credstash put foo bar
foo has been stored
scramble:credstash dom-at-luminal$ ./credstash put foo baz
foo version 1 is already in the credential store. Use the -v flag to specify a new version
scramble:credstash dom-at-luminal$ ./credstash put foo baz -a
foo has been stored
scramble:credstash dom-at-luminal$ ./credstash put vers bar -v 1.1.9
vers has been stored
scramble:credstash dom-at-luminal$ ./credstash put vers baz -v 1.2.0
vers has been stored
scramble:credstash dom-at-luminal$ ./credstash put dttm bar -v 20151105
dttm has been stored
scramble:credstash dom-at-luminal$ ./credstash put dttm baz -v 20151106
dttm has been stored …
```
> Tweak to migration, README update

- credstash.py
Expose errors in the credstash exit code, and add logging of a
previously-swallowed exception.
> Improve error-handling.

- credstash.py
We weren't actually checking whether the region passed on the
command-line was valid, but rather whether there was a default region
available via either .aws/config or the environment. If there was no
such region, we would unconditionally fall back on DEFAULT_REGION,
instead of trying the one passed on the command line.
> Fix the test for whether a region is valid.

- credstash.py
Python3 dropped 'has_key' from the dict API.
> Remove use of 'has_key'

- README.md
- credstash.py
I've added support for assuming an IAM role in another account. This normally can be done via the `aws` config file however not in the case of an EC2 instance with an IAM instance profile. Just for clarification Ill go over my configuration:
* EC2 instance: Attached with instance profile:
```
{
"Statement": [
{
"Resource": [
"arn:aws:iam::0000002:role/credstash"
],
"Action": [
"sts:AssumeRole"
],
"Effect": "Allow"
}
]
}
```
* IAM role: Trust Relationship to `account-0000001` and permissions:
```
{
"Version": "2012-10-17",
"Statement": [
{
"Sid": "",
"Effect": "Allow",
"Principal": {
"AWS": "arn:aws:iam::0000001:root"
},
"Action": "sts:AssumeRole"
}
]
}
```
```
{
"Version": "2012-10-17",
"Statement": [
{
"Action": [
"kms:Decrypt",
"kms:CreateGrant"
],
"Effect": "Allow",
"Resource": …
```
> Adding IAM Assumerole Support

- README.md
This policy allows you to get or read, not "put" secrets.
> correct secret reader iam policy description

- credstash.py
- only applied it to the list though
- pulled th parsers generation into a helper function
I'd like to pull out each of the other actions into functions and do the same, and split up the parser function some more.
More of a RFC than a please merge this now;
> Create a decorator so failed commands cleanly exit

- credstash.py
The logic for the putSecret function previously required a version, but performed a default check in the function to add a padded 1 if the version is set to an empty string. This commit sets `version` to an empty string by default in order to take advantage of the default value when a library user does not provide a version. This change should not break current integrations with the library.
> Allow default version for putSecret

- credstash.py
- setup.py
I was interested in this as well and decided to undertake it. This provides an export dotenv format (key=value) option requested in issue #76 . I'm a bit iffy with regards to the name (dotenv) but couldn't think of anything better - looking forward to your thoughts on that, too. Thanks!
> Support dotenv getall export format

- credstash.py
I wasn't able to find a convenient way to get secrets by wildcard programmatically, when using credstash as a library in a Python program. 
It's possible to use the existing `getSecretAction` passing in an `args` object with a `credential` attribute containing a wildcard, but that requires the client to know too much about the internals of `credstash`. It's also possible to use `getAllSecrets` and filter the secrets on the wildcard after the fact, but that requires every library user to implement their own filtering.
So in order to make `credstash` filtering work out of the box when used programmatically, I added an optional `credential` argument to `getAllSecrets`, which is used to filter out secrets whose `name` doesn't match the `credential` wildcard pattern before returning the …
> Get secrets by wildcard when using as a library

- requirements.txt
- setup.py
The [update to Cryptography today](https://cryptography.io/en/latest/changelog/#id1) broke our builds.
Is this something you would consider merging posthaste? It would be *very* appreciated!
I tested `get` and `put` commands via the `credstash` CLI to verify that this can be done safely. I'm uncertain though if this change has further implications. I just assumed that it is some legacy holdover.
Thanks!
> Remove <2.0 cryptography constraint

- requirements.txt
- setup.py
In version 2.1 of cryptography, support for RIPEMD160 hashes got removed (see cryptography [`master`](https://github.com/pyca/cryptography/blob/master/src/cryptography/hazmat/primitives/hashes.py#L145)  vs [`2.0.x`](https://github.com/pyca/cryptography/blob/2.0.x/src/cryptography/hazmat/primitives/hashes.py#L145) ), but Credstash still points to those.
I chose to modify setup.py rather than remove that hash family from credstash, as that would probably be disruptive for other users of `credstash`.
> Force cryptography<2.1

- credstash.py
I often find that I want to know what keys exist, but not how many versions.
This adds `credstash keys` to just print out the list of credentials without versions.
> Add option to list unique keys

- README.md
- credstash.py
This PR
* Updates the credstash `usage` in the README to match the current `usage` produced by credstash itself
* Fixes some inconsistent indentation in the `usage` in the README
* Adds details to the documentation on the use of passing a filename or using stdin for secrets
* Adds to the documentation how to install the optional YAML support
* Fixes a typo in the usage text in credstash
> Documentation improvements

- credstash.py
I'm not sure how to write tests for this in a cross-platform manner. Is it possible to change which operating system a python script thinks it is in at runtime?
I did confirm this change adds the appropriate line ending for my linux machine:
```
$ credstash getall -f csv > blah.txt
$ ag "\r\n"
blah.txt
1:kek,test
2:test.ca-pemfile.crl,test
3:test.server-cert.crt,test
4:test.client-ca.crt,test
5:manufacturerKey,test
6:test.server-cert.key,test
7:
$ credstash getall -f csv > blah.txt
$ ag "\r\n"
```
> Resolves #102: Adds os-specific newline characters

- credstash_migrate_digests.py
Cryptography module update past 2.1 breaks `credstash` because `cryptography` no longer supports the `RIPEMD-160` or `Whirlpool` hash functions. Credstash will presumably be updated to remove those hashes (there are pull requests in to do so), however anyone using the deprecated hash functions in their dynamodb table will be unable to access those secrets when `credstash` removes support for them. This script automagically searches all your dynamodb table entries, gets the latest version of secrets, and if that version uses `RIPEMD-160` or `Whirlpool`, updates the digest to `SHA256` and increments the version; it does not delete the old version. This will pave the way for people using `Whirlpool` or `RIPEMD-160` to not have their secrets stranded in the future without downgrading …
> Migrates any Whirlpool/RIPEMD-160 digests to SHA256 :tada:

- credstash.py
This PR adds quotes for the key/value pairs ouptut with the dotenv output format.  The new output will now look like:
```
key='value'
key2='other value'
```
> Add quotes for dotenv output

- README.md
- a modification of the readme file to show how to export the AWS_PROFILE for Credstash usage with multiple AWS accounts
> update readme to show usage with multiple AWS accounts

- credstash.py
Adding support for storing and retrieving binary secrets. Files are read in using binary mode, and output to stdout in binary mode.
Example usage:
```bash
echo "test" | gzip > test.gz
credstash put test_key @test.gz
credstash get test_key | gunzip
```
To facilitate this working smoothly, the argument `--noline` was deprecated (as it's now the default behavior) and added `--newline` to add a newline to output for scripts that want it.
```bash
credstash get -n test_key
credstash get -e test_key
```
> Resolves #73: Support binary secrets

- README.md
- credstash.py
- tests/key_pair_tests.py
adds a `--tags` to `credstash setup`
Can be used as `credstash -t some-new-table setup --tags MyTag=MyValue AnotherTag=AnotherValue`
> Ability to tag new tables, Resolves #233

- credstash.py
> Set args.comment to None when using putall.

- credstash.py
Currently running the `put all` operation leads to this error: 
```
"credstash.py”, line 386, in putSecretAction
context=args.context, digest=args.digest, comment=args.comment,
AttributeError: ‘Namespace’ object has no attribute ‘comment’
```
This is because the comment is not an argument for the putall operation but `put` is expecting `comment`.
Adding the comment to the putall operation solves the problem and it also makes sense to add a comment in the bulk put operation.
> Add comment option to the put all operation

- credstash.py
AttributeError: 'Namespace' object has no attribute 'prompt'
It's not needed for this operation anyhow.
> putall fails because prompt attribute is missing

- credstash.py
When using the getAllSecrets function, I want to be able to pass a session object
with custom profile/key and region information.
Currently, it uses the default AWS profile and is not configurable because of 
this nuance.
> Allow use of a custom session with AWS profile information when using the getAllSecrets

- credstash.py
Hi guys,
Thanks for this software.
We recently upgraded our python to 3.8 to test the compatibility and when running credstash we get the following warnings:
```
/usr/local/bin/credstash.py:111: SyntaxWarning: "is not" with a literal. Did you mean "!="?
self.value = "KMS ERROR: " + value if value is not "" else "KMS ERROR"
/usr/local/bin/credstash.py:120: SyntaxWarning: "is not" with a literal. Did you mean "!="?
self.value = "INTEGRITY ERROR: " + value if value is not "" else \
```
This PR fixes those.
These warnings are problematic when you use the result of the credstash output in a variable using `$()`.
Thanks
> Fix SyntaxWarnings showing up in python 3.8

- credstash.py
- tests/get_session_tests.py
Resolves #255 
Currently, `get_session` caches sessions in a single variable, and the cached session takes priority over explicitly-passed-in parameters. This means that there can only be a single `Session` each time `credstash` is imported, which is set the first time `get_session` is called. All subsequent calls to `get_session` return that session, regardless of input.
This PR adds aliased caching by `aws_access_key_id` to `get_session`. On the first call with any `aws_access_key_id`, a `Session` is created and stored in a dictionary. All subsequent calls with that AKID will re-use the cached `Session`. The existing caching behavior, where a call to `get_session` returns the last-used `Session` is maintained using a `last_session` variable. 
Both the cache and `last_session` can be …
> Alias cached sessions

- README.md
- credstash.py
References #256 
Currently, `credstash` only handles AWS ClientErrors by logging the error message to `stderr`. This is sufficient for most AWS errors, but doesn't handle non-AWS errors. This PR adds exception handling for all exceptions, and adds a configurable log file that includes the full stack trace.
> Issue #256 Add configurable logging and log ALL exceptions

- credstash.py
- tests/get_session_test.py
We use credstash on our Jenkins workers. The workers use Role based authentication, we have only a ~/.aws/config file, no credentials. When we upgraded to v1.16.2 we started seeing errors:
An error occurred (AccessDeniedException) when calling the Query operation: User: arn:aws:sts::111111111:assumed-role/RoleNameOfDefaultProfile/botocore-session-333333333 is not authorized to perform: dynamodb:Query on resource: arn:aws:dynamodb:us-east-1:111111111:table/secret-credential-store
credstash was not using the profile we passed in with the -p parameter.  After debugging, I discovered it was because boto3.Session() was being called with no parameters and therefore defaulted to the "default" profile.
> Update get_session() to allow using only profile_name and no access/secret keys

- credstash.py
- integration_tests/test_kms_region.bats
Resolves #257.
This PR adds a new top-level command-line argument, `--kms-region`. 
```
credstash --kms-region us-east-1 --region us-east-2 put secret1 secretvalue
credstash --kms-region us-east-1 --region us-east-2 putall '{"secret": "secretvalue"}'
credstash --kms-region us-east-1 --region us-east-2 get secret1
credstash --kms-region us-east-1 --region us-east-2 getall
```
This argument allows users to set the region from which the `credstash` KMS Key should be read separately from the region in which the `credstash` DynamoDB Table is stored. This allows `credstash` to be used with [DynamoDB Global Tables](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/globaltables_HowItWorks.html) with minimal AWS configuration.
Note that the KMS region can be specified for `keys`, …
> Add --kms-region argument

- credstash.py
Removing explicit log file creation when imported as library. This is causing issue when process don't have permission to create log file. 
#271 #273
> Resolves #271 #273: Remove explicit logger

- credstash.py
Resolves #269 
* Remove reference to `logger.hasHandlers()` for better Python 2 compatibility
* Remove type hints and format strings for Python 2 compatibility
> CS-269 remove reference to hasHandlers() for python 2 compatibility

- credstash.py
`FileNotFoundError` does not exist in Python 2, so fall back to `IOError`.
> use IOError instead of FileNotFoundError

- credstash.py
Move `kms_region` optional parameter to end of optional parameters to preserve existing functionality when optional parameters were used positionally.
> CS-291 move kms_region to end of named params

- credstash.py
`putSecretAutoversion` forgets to pass `region` to `getHighestVersion` which will end in an exception
> pass 'region' to 'getHighestVersion'

- README.md
Hi there - We have developed a Credstash Operator for Kubernetes and have been using it in production for several months now. We think it might be worth adding a link to it for others that might find it useful.
https://github.com/ouzi-dev/credstash-operator
> doc: add link to k8s credstash operator
